# fly.toml app configuration file generated for ph-beam on 2025-10-13T19:58:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ph-beam'
primary_region = 'ord'

[env]
  DATABASE_PATH = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
